name: OWASP ZAP Full Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  zap_full_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare Reports Folder
        run: mkdir -p zap_reports

      - name: Run OWASP ZAP Full Scan
        run: |
          docker run --rm \
            -v $(pwd)/zap_reports:/zap/wrk:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-full-scan.py \
              -t http://testphp.vulnweb.com \
              -J report.json \
              -w report.md \
              -r report.html \
              -x report.xml \
              -a -j -I \
              -z "-Xmx1024m"

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-full-reports
          path: zap_reports

      - name: Show Markdown Summary
        run: |
          echo "===== ZAP SUMMARY ====="
          cat zap_reports/report.md || echo "No markdown report found"
