name: OWASP ZAP Full Scan

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  zap_full_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare Reports Folder
        run: mkdir -p zap_reports

      - name: Run OWASP ZAP Full Scan
        run: |
          docker run --rm -u $(id -u):$(id -g) \
            -v $(pwd)/zap_reports:/zap/wrk:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-full-scan.py \
              -t http://testphp.vulnweb.com \
              -J report.json \
              -w report.md \
              -r report.html \
              -x report.xml \
              -a -j -I

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-full-reports
          path: zap_reports
